name: C++ Lint

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [ main, master ]

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run C++ Linter
        id: linter
        uses: cpp-linter/cpp-linter-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file'
          tidy-checks: ''
          thread-comments: ${{ github.event_name == 'pull_request' && 'update' }}
          files-changed-only: true

      - name: Fail if checks failed
        if: steps.linter.outputs.checks-failed > 0
        run: exit 1
